name: places
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0

  provider: ^5.0.0
  shared_preferences: ^2.0.6

  dio: ^4.0.0

  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  rxdart: ^0.27.1

  moor: ^4.3.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  path: ^1.8.0

  image_picker: ^0.8.0
  http_parser: ^4.0.0
  mime_type: ^1.0.0

  geolocator: ^7.0.3
  yandex_mapkit: ^1.0.0
  maps_launcher: ^2.0.0

  share_plus: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^4.3.1
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: false
  image_path: 'res/icons/app_dev.png'

flutter:

  uses-material-design: true

  assets:
    - res/
    - res/icons/
    - res/icons/catalog/
    - res/icons/tutorial/
    - res/icons/empty_pages/
    - res/icons/loader/
    - res/icons/map/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: res/fonts/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto-Black.ttf
          weight: 900
        - asset: res/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: res/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
